#!/bin/python
import math
import os
import random
import re
import sys
def solve(s):
    s=" "+s
    for x in range(len(s)):
        if s[x]==" ":
           a=s[x+1].upper()
           s=s[0,x]+a+s[:x+1]
    return s
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')
    s = raw_input()
    result = solve(s)
    fptr.write(result + '\n')
    fptr.close()
